//! WebAuthn signature verification for passkey `/finish` handlers.
//!
//! Pure functions. No HTTP, no storage, no I/O. Implements the contract
//! described in `spec/v1/server.md` §6.2: ES256 / EC2 P-256 only, opaque
//! errors, atomic challenge consumption is the caller's responsibility.
//!
//! The verifier is exercised against `spec/v1/webauthn.vectors.json` —
//! fixtures generated by an INDEPENDENT Python implementation. Two
//! unrelated codebases agreeing on the same bytes is the correctness
//! signal; this module's own helpers must never be used to generate the
//! fixtures it is later tested against.

use ring::digest::{digest, SHA256};
use ring::signature::{UnparsedPublicKey, ECDSA_P256_SHA256_ASN1};

/// All verifier failures. Mapped to opaque `401 unauthorized` by callers
/// (the discriminator is logged server-side, never returned to clients —
/// distinguishing variants over the wire would give an attacker a free
/// oracle). Variant names match `expected.error` in `webauthn.vectors.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VerifyError {
    AuthenticatorDataMalformed,
    RpIdHashMismatch,
    UserPresentFlagNotSet,
    AttestedCredentialDataAbsent,
    AttestedCredentialDataMalformed,
    UnsupportedCoseAlgorithm,
    CoseKeyMalformed,
    ClientDataJsonMalformed,
    ClientDataTypeMismatch,
    ChallengeMismatch,
    OriginMismatch,
    SignCountRegressed,
    InvalidSignature,
}

impl VerifyError {
    /// Stable string discriminator used in logs and test vectors.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AuthenticatorDataMalformed => "AuthenticatorDataMalformed",
            Self::RpIdHashMismatch => "RpIdHashMismatch",
            Self::UserPresentFlagNotSet => "UserPresentFlagNotSet",
            Self::AttestedCredentialDataAbsent => "AttestedCredentialDataAbsent",
            Self::AttestedCredentialDataMalformed => "AttestedCredentialDataMalformed",
            Self::UnsupportedCoseAlgorithm => "UnsupportedCoseAlgorithm",
            Self::CoseKeyMalformed => "CoseKeyMalformed",
            Self::ClientDataJsonMalformed => "ClientDataJsonMalformed",
            Self::ClientDataTypeMismatch => "ClientDataTypeMismatch",
            Self::ChallengeMismatch => "ChallengeMismatch",
            Self::OriginMismatch => "OriginMismatch",
            Self::SignCountRegressed => "SignCountRegressed",
            Self::InvalidSignature => "InvalidSignature",
        }
    }
}

// ── Authenticator-data layout (W3C WebAuthn §6.1) ─────────────────────

const FLAG_UP: u8 = 0x01;
const FLAG_AT: u8 = 0x40;

/// Parsed prefix of an authenticatorData blob (the bytes shared by login
/// and registration ceremonies).
struct AuthDataPrefix<'a> {
    rp_id_hash: &'a [u8; 32],
    flags: u8,
    sign_count: u32,
    /// Bytes following the prefix — the attested-credential-data section
    /// when the AT flag is set, empty otherwise.
    rest: &'a [u8],
}

/// Parse `rpIdHash(32) || flags(1) || signCount(4 BE) || rest`.
fn split_auth_data(auth: &[u8]) -> Result<AuthDataPrefix<'_>, VerifyError> {
    if auth.len() < 37 {
        return Err(VerifyError::AuthenticatorDataMalformed);
    }
    let rp_id_hash: &[u8; 32] = auth[0..32]
        .try_into()
        .map_err(|_| VerifyError::AuthenticatorDataMalformed)?;
    let flags = auth[32];
    let sign_count = u32::from_be_bytes(
        auth[33..37]
            .try_into()
            .map_err(|_| VerifyError::AuthenticatorDataMalformed)?,
    );
    Ok(AuthDataPrefix {
        rp_id_hash,
        flags,
        sign_count,
        rest: &auth[37..],
    })
}

fn rp_id_hash(rp_id: &str) -> [u8; 32] {
    let d = digest(&SHA256, rp_id.as_bytes());
    let mut out = [0u8; 32];
    out.copy_from_slice(d.as_ref());
    out
}

// ── COSE_Key parsing (RFC 9052 §7) ─────────────────────────────────────

/// Parse a COSE_Key for EC2 P-256 / ES256. Returns the SEC1 uncompressed
/// point `0x04 || X || Y` (65 bytes), which is the canonical form ring's
/// ECDSA verifier consumes and what we persist in the passkey row.
///
/// Strict: rejects any kty != 2 (EC2), alg != -7 (ES256), crv != 1 (P-256),
/// missing X/Y, or X/Y not exactly 32 bytes. Returns the bytes consumed so
/// the caller can verify there's no trailing data after the COSE_Key.
fn parse_cose_key_ec2_p256(input: &[u8]) -> Result<(Vec<u8>, usize), VerifyError> {
    let mut p = CborParser::new(input);
    let n = p.map_header().ok_or(VerifyError::CoseKeyMalformed)?;
    if n == 0 || n > 16 {
        return Err(VerifyError::CoseKeyMalformed);
    }

    let mut kty: Option<i64> = None;
    let mut alg: Option<i64> = None;
    let mut crv: Option<i64> = None;
    let mut x: Option<&[u8]> = None;
    let mut y: Option<&[u8]> = None;

    for _ in 0..n {
        let key = p.int().ok_or(VerifyError::CoseKeyMalformed)?;
        match key {
            1 => kty = Some(p.int().ok_or(VerifyError::CoseKeyMalformed)?),
            3 => alg = Some(p.int().ok_or(VerifyError::CoseKeyMalformed)?),
            -1 => crv = Some(p.int().ok_or(VerifyError::CoseKeyMalformed)?),
            -2 => x = Some(p.bstr().ok_or(VerifyError::CoseKeyMalformed)?),
            -3 => y = Some(p.bstr().ok_or(VerifyError::CoseKeyMalformed)?),
            _ => {
                p.skip().ok_or(VerifyError::CoseKeyMalformed)?;
            }
        }
    }

    if kty != Some(2) {
        return Err(VerifyError::UnsupportedCoseAlgorithm);
    }
    if alg != Some(-7) {
        return Err(VerifyError::UnsupportedCoseAlgorithm);
    }
    if crv != Some(1) {
        return Err(VerifyError::UnsupportedCoseAlgorithm);
    }
    let x = x.ok_or(VerifyError::CoseKeyMalformed)?;
    let y = y.ok_or(VerifyError::CoseKeyMalformed)?;
    if x.len() != 32 || y.len() != 32 {
        return Err(VerifyError::CoseKeyMalformed);
    }

    let mut sec1 = Vec::with_capacity(65);
    sec1.push(0x04);
    sec1.extend_from_slice(x);
    sec1.extend_from_slice(y);
    Ok((sec1, p.consumed()))
}

/// Minimal CBOR parser scoped to the shapes a COSE_Key for EC2 P-256 can
/// take (RFC 9052 §7). Refuses anything beyond what we need: small-int
/// keys, definite-length maps, byte strings.
struct CborParser<'a> {
    buf: &'a [u8],
    pos: usize,
}

impl<'a> CborParser<'a> {
    fn new(buf: &'a [u8]) -> Self {
        Self { buf, pos: 0 }
    }

    fn consumed(&self) -> usize {
        self.pos
    }

    fn next_byte(&mut self) -> Option<u8> {
        let b = *self.buf.get(self.pos)?;
        self.pos += 1;
        Some(b)
    }

    fn read_uint(&mut self, info: u8) -> Option<u64> {
        match info {
            0..=23 => Some(info as u64),
            24 => self.next_byte().map(u64::from),
            25 => {
                if self.pos + 2 > self.buf.len() {
                    return None;
                }
                let v = u16::from_be_bytes([self.buf[self.pos], self.buf[self.pos + 1]]);
                self.pos += 2;
                Some(v as u64)
            }
            26 => {
                if self.pos + 4 > self.buf.len() {
                    return None;
                }
                let v = u32::from_be_bytes(self.buf[self.pos..self.pos + 4].try_into().ok()?);
                self.pos += 4;
                Some(v as u64)
            }
            _ => None, // 27 (u64), 28-30 (reserved), 31 (indefinite) all unsupported
        }
    }

    /// Reads a map header, returns the number of pairs.
    fn map_header(&mut self) -> Option<u64> {
        let head = self.next_byte()?;
        let major = head >> 5;
        let info = head & 0x1f;
        if major != 5 {
            return None;
        }
        self.read_uint(info)
    }

    /// Reads an integer (major 0 or 1) as i64.
    fn int(&mut self) -> Option<i64> {
        let head = self.next_byte()?;
        let major = head >> 5;
        let info = head & 0x1f;
        let raw = self.read_uint(info)?;
        let signed = i64::try_from(raw).ok()?;
        match major {
            0 => Some(signed),
            1 => Some(-1 - signed),
            _ => None,
        }
    }

    /// Reads a byte string (major 2). Returns a slice into the original buffer.
    fn bstr(&mut self) -> Option<&'a [u8]> {
        let head = self.next_byte()?;
        let major = head >> 5;
        let info = head & 0x1f;
        if major != 2 {
            return None;
        }
        let n = self.read_uint(info)? as usize;
        if self.pos + n > self.buf.len() {
            return None;
        }
        let s = &self.buf[self.pos..self.pos + n];
        self.pos += n;
        Some(s)
    }

    /// Skip a single CBOR data item without inspecting its contents.
    /// Limited support: ints, bstrs, tstrs, arrays, maps. Recurses on
    /// container items. Returns Some(()) on success.
    fn skip(&mut self) -> Option<()> {
        let head = self.next_byte()?;
        let major = head >> 5;
        let info = head & 0x1f;
        let n = self.read_uint(info)?;
        match major {
            0 | 1 => Some(()),
            2 | 3 => {
                let n = n as usize;
                if self.pos + n > self.buf.len() {
                    return None;
                }
                self.pos += n;
                Some(())
            }
            4 => {
                for _ in 0..n {
                    self.skip()?;
                }
                Some(())
            }
            5 => {
                for _ in 0..n {
                    self.skip()?; // key
                    self.skip()?; // value
                }
                Some(())
            }
            _ => None,
        }
    }
}

// ── clientDataJSON parsing (W3C WebAuthn §5.10.1) ──────────────────────

/// Validate the structural fields of clientDataJSON. Does NOT canonicalize:
/// we parse the literal bytes the browser sent and compare expected values
/// as strings. Returns Ok(()) on match, with the specific error otherwise.
fn check_client_data(
    bytes: &[u8],
    expected_type: &str,
    expected_challenge_b64u: &str,
    expected_origin: &str,
) -> Result<(), VerifyError> {
    let v: serde_json::Value =
        serde_json::from_slice(bytes).map_err(|_| VerifyError::ClientDataJsonMalformed)?;
    let obj = v.as_object().ok_or(VerifyError::ClientDataJsonMalformed)?;

    let ty = obj
        .get("type")
        .and_then(|x| x.as_str())
        .ok_or(VerifyError::ClientDataJsonMalformed)?;
    if ty != expected_type {
        return Err(VerifyError::ClientDataTypeMismatch);
    }

    let challenge = obj
        .get("challenge")
        .and_then(|x| x.as_str())
        .ok_or(VerifyError::ClientDataJsonMalformed)?;
    if challenge != expected_challenge_b64u {
        return Err(VerifyError::ChallengeMismatch);
    }

    let origin = obj
        .get("origin")
        .and_then(|x| x.as_str())
        .ok_or(VerifyError::ClientDataJsonMalformed)?;
    if origin != expected_origin {
        return Err(VerifyError::OriginMismatch);
    }

    Ok(())
}

// ── Public API ─────────────────────────────────────────────────────────

/// What `parse_registration` returns when the attested credential data
/// successfully validates. The caller persists `credential_id` and
/// `public_key_sec1` (base64url, in the passkey row) and uses
/// `sign_count` as the initial value for the row.
#[derive(Debug, Clone)]
pub struct ParsedRegistration {
    pub credential_id: Vec<u8>,
    pub public_key_sec1: Vec<u8>,
    pub sign_count: u32,
}

/// Verify the structural and cryptographic invariants of a register-finish
/// or add-finish ceremony. Returns the parsed credential on success.
pub fn parse_registration(
    authenticator_data: &[u8],
    client_data_json: &[u8],
    expected_challenge_b64u: &str,
    expected_origin: &str,
    expected_rp_id: &str,
) -> Result<ParsedRegistration, VerifyError> {
    check_client_data(
        client_data_json,
        "webauthn.create",
        expected_challenge_b64u,
        expected_origin,
    )?;

    let prefix = split_auth_data(authenticator_data)?;
    if prefix.rp_id_hash != &rp_id_hash(expected_rp_id) {
        return Err(VerifyError::RpIdHashMismatch);
    }
    if prefix.flags & FLAG_UP == 0 {
        return Err(VerifyError::UserPresentFlagNotSet);
    }
    if prefix.flags & FLAG_AT == 0 {
        return Err(VerifyError::AttestedCredentialDataAbsent);
    }

    // Layout (§6.5.4): aaguid(16) || credIdLen(2 BE) || credentialId || credentialPublicKey(COSE_Key).
    let rest = prefix.rest;
    if rest.len() < 18 {
        return Err(VerifyError::AttestedCredentialDataMalformed);
    }
    let cred_id_len = u16::from_be_bytes(
        rest[16..18]
            .try_into()
            .map_err(|_| VerifyError::AttestedCredentialDataMalformed)?,
    ) as usize;
    if rest.len() < 18 + cred_id_len {
        return Err(VerifyError::AttestedCredentialDataMalformed);
    }
    let credential_id = rest[18..18 + cred_id_len].to_vec();
    let cose_input = &rest[18 + cred_id_len..];
    let (public_key_sec1, _consumed) = parse_cose_key_ec2_p256(cose_input)?;

    Ok(ParsedRegistration {
        credential_id,
        public_key_sec1,
        sign_count: prefix.sign_count,
    })
}

pub struct AssertionContext<'a> {
    pub stored_pubkey_sec1: &'a [u8],
    pub stored_sign_count: u32,
    pub expected_challenge_b64u: &'a str,
    pub expected_origin: &'a str,
    pub expected_rp_id: &'a str,
}

pub struct AssertionRequest<'a> {
    pub authenticator_data: &'a [u8],
    pub client_data_json: &'a [u8],
    pub signature: &'a [u8],
}

/// Verify a login assertion. Returns the new sign_count on success — the
/// caller persists it before issuing a session token.
pub fn verify_assertion(
    ctx: &AssertionContext,
    req: &AssertionRequest,
) -> Result<u32, VerifyError> {
    check_client_data(
        req.client_data_json,
        "webauthn.get",
        ctx.expected_challenge_b64u,
        ctx.expected_origin,
    )?;

    let prefix = split_auth_data(req.authenticator_data)?;
    if prefix.rp_id_hash != &rp_id_hash(ctx.expected_rp_id) {
        return Err(VerifyError::RpIdHashMismatch);
    }
    if prefix.flags & FLAG_UP == 0 {
        return Err(VerifyError::UserPresentFlagNotSet);
    }

    // Sign-count rule (W3C WebAuthn §6.1.1): if the new value is non-zero, it
    // must be strictly greater than the stored value. A new value of 0 is
    // allowed only when the stored value is also 0 (some authenticators —
    // notably Apple's synced passkeys — never increment).
    let new_sign_count = prefix.sign_count;
    if !(new_sign_count == 0 && ctx.stored_sign_count == 0)
        && new_sign_count <= ctx.stored_sign_count
    {
        return Err(VerifyError::SignCountRegressed);
    }

    let mut signed = Vec::with_capacity(req.authenticator_data.len() + 32);
    signed.extend_from_slice(req.authenticator_data);
    signed.extend_from_slice(digest(&SHA256, req.client_data_json).as_ref());

    let pk = UnparsedPublicKey::new(&ECDSA_P256_SHA256_ASN1, ctx.stored_pubkey_sec1);
    pk.verify(&signed, req.signature)
        .map_err(|_| VerifyError::InvalidSignature)?;

    Ok(new_sign_count)
}

#[cfg(test)]
mod tests {
    use super::*;
    use base64::engine::general_purpose::URL_SAFE_NO_PAD;
    use base64::Engine;

    fn b64u(s: &str) -> Vec<u8> {
        URL_SAFE_NO_PAD.decode(s).expect("base64url")
    }

    fn load_vectors() -> serde_json::Value {
        let path = concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../spec/v1/webauthn.vectors.json"
        );
        let bytes = std::fs::read(path).expect("read webauthn.vectors.json");
        serde_json::from_slice(&bytes).expect("parse webauthn.vectors.json")
    }

    /// Iterate every fixture in the spec file and assert the verifier's
    /// behavior matches. This is the load-bearing correctness test —
    /// fixtures are produced by an independent Python implementation.
    #[test]
    fn spec_vectors_round_trip() {
        let v = load_vectors();
        let vectors = v["vectors"].as_array().expect("vectors array");
        assert!(!vectors.is_empty(), "vectors file is empty");

        for vec in vectors {
            let name = vec["name"].as_str().expect("name");
            let kind = vec["kind"].as_str().expect("kind");
            let inputs = &vec["inputs"];
            let expected = &vec["expected"];

            match kind {
                "register" => check_register(name, inputs, expected),
                "verify" => check_verify(name, inputs, expected),
                other => panic!("vector {name}: unknown kind {other}"),
            }
        }
    }

    fn check_register(name: &str, inputs: &serde_json::Value, expected: &serde_json::Value) {
        let auth = b64u(inputs["authenticator_data_b64u"].as_str().unwrap());
        let cdj = b64u(inputs["client_data_json_b64u"].as_str().unwrap());
        let challenge = inputs["expected_challenge_b64u"].as_str().unwrap();
        let origin = inputs["origin"].as_str().unwrap();
        let rp_id = inputs["rp_id"].as_str().unwrap();

        let result = parse_registration(&auth, &cdj, challenge, origin, rp_id);

        if expected["ok"].as_bool() == Some(true) {
            let parsed = result.unwrap_or_else(|e| panic!("vector {name}: expected ok, got {e:?}"));
            let want_cred = b64u(expected["credential_id_b64u"].as_str().unwrap());
            let want_pub = b64u(expected["stored_pubkey_b64u"].as_str().unwrap());
            assert_eq!(parsed.credential_id, want_cred, "{name}: credential_id");
            assert_eq!(parsed.public_key_sec1, want_pub, "{name}: stored_pubkey");
            assert_eq!(
                parsed.sign_count as u64,
                expected["sign_count"].as_u64().unwrap(),
                "{name}: sign_count"
            );
        } else {
            let err = result.expect_err(&format!("vector {name}: expected error"));
            let want = expected["error"].as_str().unwrap();
            assert_eq!(err.as_str(), want, "{name}: error variant");
        }
    }

    fn check_verify(name: &str, inputs: &serde_json::Value, expected: &serde_json::Value) {
        let pubkey = b64u(inputs["stored_pubkey_b64u"].as_str().unwrap());
        let auth = b64u(inputs["authenticator_data_b64u"].as_str().unwrap());
        let cdj = b64u(inputs["client_data_json_b64u"].as_str().unwrap());
        let sig = b64u(inputs["signature_b64u"].as_str().unwrap());
        let stored_count = inputs["stored_sign_count"].as_u64().unwrap() as u32;
        let challenge = inputs["expected_challenge_b64u"].as_str().unwrap();
        let origin = inputs["origin"].as_str().unwrap();
        let rp_id = inputs["rp_id"].as_str().unwrap();

        let ctx = AssertionContext {
            stored_pubkey_sec1: &pubkey,
            stored_sign_count: stored_count,
            expected_challenge_b64u: challenge,
            expected_origin: origin,
            expected_rp_id: rp_id,
        };
        let req = AssertionRequest {
            authenticator_data: &auth,
            client_data_json: &cdj,
            signature: &sig,
        };
        let result = verify_assertion(&ctx, &req);

        if expected["ok"].as_bool() == Some(true) {
            let new_count =
                result.unwrap_or_else(|e| panic!("vector {name}: expected ok, got {e:?}"));
            assert_eq!(
                new_count as u64,
                expected["new_sign_count"].as_u64().unwrap(),
                "{name}: new_sign_count"
            );
        } else {
            let err = result.expect_err(&format!("vector {name}: expected error"));
            let want = expected["error"].as_str().unwrap();
            assert_eq!(err.as_str(), want, "{name}: error variant");
        }
    }
}
